kind: pipeline
type: docker
name: node-build

steps:
  - name: install-dependencies
    image: node:18
    commands:
      - npm install

  - name: copy-build-to-server
    image: appleboy/drone-scp
    settings:
      host: 192.168.33.16
      username: assafco
      password: 12345  # Use secrets instead of plain text (see below)
      port: 22
      source: "*"
      target: "/var/www/html/projects-server"  # Change this to your target folder

  - name: start-app
    image: node:18
    commands:
      - npm install
      - npm run build
      - npm start
    ports:
      - 3000